/*
 * generated by Xtext 2.29.0.M3
 */
package beetween.com.mp.connector.generator.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class ConnectorGeneratorScopeProvider extends AbstractConnectorGeneratorScopeProvider {

}
