/*
 * generated by Xtext 2.29.0.M3
 */
package beetween.com.mp.connector.generator;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConnectorGeneratorRuntimeModule extends AbstractConnectorGeneratorRuntimeModule {
}
