/*
 * generated by Xtext 2.29.0.M3
 */
package beetween.com.mp.connector.generator;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ConnectorGeneratorStandaloneSetup extends ConnectorGeneratorStandaloneSetupGenerated {

	public static void doSetup() {
		new ConnectorGeneratorStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
